title: "Random Thoughts on Economics from a Non‑Expert"
description: "経済(学)について思う事をつぶやきます。"

url: "https://tokyo-worker.github.io"
baseurl: ""

lang: ja
timezone: Asia/Tokyo

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown

kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge

  parse_block_html: true
  
permalink: /:title/

minimal_mistakes_skin: default

header_pages:
  - archive.md
  - about.md

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: single
      toc: true
      toc_sticky: true
